import Head from "next/head";
import Image from "next/image";
import {useRouter} from "next/router";
import {useEffect, useState} from "react";
import {
    useAccount,
    useConnect,
} from "wagmi";
import {Dialog} from '@headlessui/react'
import styles from "../styles/Home.module.css";

/* This example requires Tailwind CSS v2.0+ */
import {Fragment} from 'react'
import {Disclosure, Menu, Transition} from '@headlessui/react'
import {BellIcon, MenuIcon, XIcon} from '@heroicons/react/outline'
import ConnectWallet from "../components/ConnectWallet";


export default function Home() {
    const {connectors, connect} = useConnect();
    const {isConnected} = useAccount();
    const router = useRouter();

    let [isOpen, setIsOpen] = useState(isConnected);

    // useEffect(() => {
    //     if (isConnected) router.replace("/dashboard");
    // }, [isConnected]);


    const user = {
        name: 'Tom Cook',
        email: 'tom@example.com',
        imageUrl:
            'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    }
    const navigation = [
        {name: 'Dashboard', href: '#', current: true},
        {name: 'Team', href: '#', current: false},
        {name: 'Projects', href: '#', current: false},
        {name: 'Calendar', href: '#', current: false},
    ]
    const userNavigation = [
        {name: 'Your Profile', href: '#'},
        {name: 'Settings', href: '#'},
        {name: 'Sign out', href: '#'},
    ]

    function classNames(...classes) {
        return classes.filter(Boolean).join(' ')
    }


    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            {/*<Dialog open={isOpen} onClose={() => setIsOpen(false)}>*/}
            {/*  <Dialog.Panel>*/}
            {/*    <Dialog.Title>Deactivate account</Dialog.Title>*/}
            {/*    <Dialog.Description>*/}
            {/*      This will permanently deactivate your account*/}
            {/*    </Dialog.Description>*/}

            {/*    <p>*/}
            {/*      Are you sure you want to deactivate your account? All of your data*/}
            {/*      will be permanently removed. This action cannot be undone.*/}
            {/*    </p>*/}

            {/*    <button onClick={() => setIsOpen(false)}>Deactivate</button>*/}
            {/*    <button onClick={() => setIsOpen(false)}>Cancel</button>*/}
            {/*  </Dialog.Panel>*/}
            {/*</Dialog>*/}

            {/*<div>*/}
            {/*  {connectors.map((connector) => (*/}
            {/*    <div>*/}
            {/*      <button*/}
            {/*        key={connector.id}*/}
            {/*        onClick={() => connect({ connector })}*/}
            {/*        type="button"*/}
            {/*        className="inline-flex items-center px-4 py-2 m-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500"*/}
            {/*      >*/}
            {/*        {connector.name}*/}
            {/*      </button>*/}
            {/*    </div>*/}
            {/*  ))}*/}
            {/*</div>*/}


            <div className="min-h-full">

                <div className="py-10">
                    <header>
                        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">

                        </div>
                    </header>
                    <main>
                        <div className="max-w-7xl mx-auto sm:px-6 lg:px-8 flex">
                            {/* Replace with your content */}
                            <div className="px-4 py-8 mt-40 sm:px-0 w-1/2">
                                <h1 className="text-3xl tracking-tight font-bold leading-tight text-gray-900 text-6xl">Make money from your audience</h1>
                                <p className="mt-4 max-w-md text-base leading-6 text-gray-500 text-xl">
                                    Monetize your content by charging your most loyal readers and reward them loyalty points and by granting them access to your pre-releases &amp; sneak-peaks.
                                </p>
                                <div className={"mt-5"}>
                                    <ConnectWallet />
                                </div>

                            </div>

                            <div className="px-4 py-8 sm:px-0 w-1/2">
                                <Image src={'/assets/images/hero.svg'} width={'600px'} height={"600px"}/>
                            </div>
                            {/* /End replace */}
                        </div>
                    </main>
                </div>
            </div>
        </div>
    );
}
