import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import {useEffect, useState} from "react";
import {
  useAccount,
  useConnect,
  useDisconnect,
  useEnsAvatar,
  useEnsName,
} from "wagmi";
import { Dialog } from '@headlessui/react'
import styles from "../styles/Home.module.css";

export default function Home() {
  const { connectors, connect } = useConnect();
  const { isConnected } = useAccount();
  const router = useRouter();

  let [isOpen, setIsOpen] = useState(isConnected);

  useEffect(() => {
    if (isConnected) router.replace("/dashboard");
  }, [isConnected]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Dialog open={isOpen} onClose={() => setIsOpen(false)}>
        <Dialog.Panel>
          <Dialog.Title>Deactivate account</Dialog.Title>
          <Dialog.Description>
            This will permanently deactivate your account
          </Dialog.Description>

          <p>
            Are you sure you want to deactivate your account? All of your data
            will be permanently removed. This action cannot be undone.
          </p>

          <button onClick={() => setIsOpen(false)}>Deactivate</button>
          <button onClick={() => setIsOpen(false)}>Cancel</button>
        </Dialog.Panel>
      </Dialog>

      <div>
        {connectors.map((connector) => (
          <div>
            <button
              key={connector.id}
              onClick={() => connect({ connector })}
              type="button"
              className="inline-flex items-center px-4 py-2 m-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500"
            >
              {connector.name}
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}
